#!/usr/bin/env bash

# shellcheck source=dev/common.sh
source dev/common.sh
# shellcheck source=scripts/common.sh
source scripts/common.sh

run "Tearing down local dev..." overmind quit --socket "$dev_overmind_sock"
