#!/usr/bin/env bash

# shellcheck source=dev/common.sh
source dev/common.sh
# shellcheck source=scripts/common.sh
source scripts/common.sh

options=$(getopt -l "gotags:" -o "t:" -a -- "$@")
eval set -- "$options"

gotags=""
while true
do
  case $1 in
    -t|--gotags)
      shift
      gotags=$1
      ;;
    --)
      shift
      break;;
  esac
  shift
done

run "Generating protobufs..." scripts/gen_pb.sh
run "Generating db implementation..." scripts/gen_db.sh
run "Running go generate..." go generate -tags="$gotags" ./...
