// Code generated by qtc from "labels.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/labels.qtpl:2
package templates

//line templates/labels.qtpl:2
import "fmt"

//line templates/labels.qtpl:3
import "strings"

//line templates/labels.qtpl:4
import "github.com/nanzhong/tstr/db"

//line templates/labels.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/labels.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/labels.qtpl:7
type LabelsPage struct {
	TestsByLabel  []db.UITestsByLabelsRow
	ResultsByTest map[string][]db.RunResult
}

//line templates/labels.qtpl:13
func (p *LabelsPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/labels.qtpl:13
	qw422016.N().S(`
Tester - Labels
`)
//line templates/labels.qtpl:15
}

//line templates/labels.qtpl:15
func (p *LabelsPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/labels.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/labels.qtpl:15
	p.StreamTitle(qw422016)
//line templates/labels.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/labels.qtpl:15
}

//line templates/labels.qtpl:15
func (p *LabelsPage) Title() string {
//line templates/labels.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/labels.qtpl:15
	p.WriteTitle(qb422016)
//line templates/labels.qtpl:15
	qs422016 := string(qb422016.B)
//line templates/labels.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/labels.qtpl:15
	return qs422016
//line templates/labels.qtpl:15
}

//line templates/labels.qtpl:18
func (p *LabelsPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/labels.qtpl:18
	qw422016.N().S(`

<div class="packages">
`)
//line templates/labels.qtpl:21
	for _, byLabel := range p.TestsByLabel {
//line templates/labels.qtpl:21
		qw422016.N().S(`
`)
//line templates/labels.qtpl:24
		labelsAsString := strings.Join(labelsAsSlice(byLabel.Labels, ": "), " ")

//line templates/labels.qtpl:25
		qw422016.N().S(`
  <div class="row mb-2">
    <div class="col">
      <h2 class="h4"><a href="/labels/`)
//line templates/labels.qtpl:28
		qw422016.E().S(fmt.Sprintf("TODO"))
//line templates/labels.qtpl:28
		qw422016.N().S(`">`)
//line templates/labels.qtpl:28
		qw422016.E().S(labelsAsString)
//line templates/labels.qtpl:28
		qw422016.N().S(`</a></h2>
      `)
//line templates/labels.qtpl:29
		for _, test := range byLabel.Tests.([]string) {
//line templates/labels.qtpl:29
			qw422016.N().S(`
        `)
//line templates/labels.qtpl:30
			for _, result := range p.ResultsByTest[test] {
//line templates/labels.qtpl:30
				qw422016.N().S(`

            `)
//line templates/labels.qtpl:32
				if result == db.RunResultPass {
//line templates/labels.qtpl:32
					qw422016.N().S(`
            <span class="badge bg-success">&nbsp;</span>
            `)
//line templates/labels.qtpl:34
				} else {
//line templates/labels.qtpl:34
					qw422016.N().S(`
            <span class="badge bg-danger">&nbsp;</span>
            `)
//line templates/labels.qtpl:36
				}
//line templates/labels.qtpl:36
				qw422016.N().S(`
        `)
//line templates/labels.qtpl:37
			}
//line templates/labels.qtpl:37
			qw422016.N().S(`
      `)
//line templates/labels.qtpl:38
		}
//line templates/labels.qtpl:38
		qw422016.N().S(`
    </div>
  </div>
`)
//line templates/labels.qtpl:41
	}
//line templates/labels.qtpl:41
	qw422016.N().S(`
</div>
`)
//line templates/labels.qtpl:43
}

//line templates/labels.qtpl:43
func (p *LabelsPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/labels.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/labels.qtpl:43
	p.StreamBody(qw422016)
//line templates/labels.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line templates/labels.qtpl:43
}

//line templates/labels.qtpl:43
func (p *LabelsPage) Body() string {
//line templates/labels.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/labels.qtpl:43
	p.WriteBody(qb422016)
//line templates/labels.qtpl:43
	qs422016 := string(qb422016.B)
//line templates/labels.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/labels.qtpl:43
	return qs422016
//line templates/labels.qtpl:43
}
